### ISSUE TITLE
Deprecation warnings should default to $stderr instead of $stdout

### ISSUE THREAD

**Issue by philandstuff** [dry-rb/dry-core#17]
An added deprecation warning in dry-types v0.12.0 caused a breakage in scale-factory/aws-assume-role.  It has a subcommand `aws-assume-role environment` where it sets environment variables by writing sourcable bash to $stdout (similar to `rbenv init -`); but the deprecation warnings emitted by dry-types caused the output to get mangled.  Writing to $stderr would have ensured that the warnings were still printed but not would not have broken the `aws-assume-role environment` command.

[scalefactory/aws-assume-rule#15](https://github.com/scalefactory/aws-assume-role/pull/15) documents some of the background.

**Comment by solnic** [comment]
Thanks for the report. I'll address this.

**Comment by philandstuff** [comment]
Thanks for the quick resolution! 💯

**Comment by solnic** [comment]
Just pushed 0.3.4 with this fix.
