### ISSUE TITLE
Dry::Core::Inflector loads ActiveSupport::Inflector

### ISSUE THREAD

**Issue by cllns** [dry-rb/dry-core#27]
I'm adding [Skylight.io](https://skylight.io) to a Hanami app. It uses stuff from ActiveSupport, but they avoid using Core Extensions (monkey patches). So, ActiveSupport is available, but the Inflector isn't used for the normal application. (It _is_ used for their CLI, but that's not being loaded here.)

The trouble is that, when Hanami uses a repository, it calls [`Dry::Core::Inflector.camelize(name)` through ROM](https://github.com/rom-rb/rom/blob/v3.3.3/lib/rom/configuration_dsl/relation.rb#L16).

By itself, this should be fine, but `Dry::Core::Inflector` attempts to load 3 different back-end engines, in this order: `ActiveSupport::Inflector`, `Dry::Inflector`, `Inflecto`. 

It first tries to require `ActiveSupport::Inflector`, which in this case succeeds, since `activesupport` is loaded. But, I don't actually want to load that :)

One way I was able to fix this was to change the order so `dry-inflector` is first, and add that to my `Gemfile`. This solves my problem, but I don't think we should be loading `ActiveSupport::Inflector` automatically. Some people use `ActiveSupport` without monkey patching, and we should encourage that. Maybe we could leverage it if it's already loaded, but not require it automatically here? 

Related: 

- https://github.com/dry-rb/dry-core/pull/8

- https://github.com/skylightio/skylight-ruby/issues/121 I originally thought this was a bug in `skylight-ruby`, but it's a bug in `dry-core`.

Happy to open a PR for this, just want to get everyone's thoughts before I move forward. I know this is an issue with ROM 3, since ROM 4 uses `rom-support`'s `Inflector`, which is actually the apparent predecessor to the `dry-core` version I'm talking about now.

**Comment by cllns** [comment]
In the title I meant that it `require`s ActiveSupport::Inflector, but that ticks don't show up in the title so I changed it to "loads", since that's more of what I mean (even though it's the `require` keyword haha).

**Comment by solnic** [comment]
This is outdated so I'm gonna close it. ROM uses Dry::Inflector now.
