### ISSUE TITLE
Child classes attributes overwrites the parent one when used as hash

### ISSUE THREAD

**Issue by mbajur** [dry-rb/dry-core#51]
## Describe the bug

Hello! I'm trying to define a simple DSL using ClassAttributes from dry-core but encountered a weird issue in the process. Please have in mind topic of instance/class variables, inheritance and all the hassles related to that are a bit challenging to me so please forgive my ignorance if I'm asking for something obvious :) I'm also not entirely sure it is a bug or just me misusing the ClassAccessor but i was asked to port that question here from Zulip so let's find out. 

## To Reproduce

```
class Base
  extend Dry::Core::ClassAttributes

  defines :exception_handlers

  def self.handle_exception(key, value)
    new_exception_handlers = exception_handlers || {}
    new_exception_handlers[key] = value
    exception_handlers new_exception_handlers
  end

  handle_exception :no_method_error, :default
end

class ClassA < Base
  handle_exception :no_method_error, :class_a_overwrite
end

class ClassB < Base
end

pp Base.exception_handlers
# => {:no_method_error=>:class_a_overwrite}

pp ClassB.exception_handlers
# => {:no_method_error=>:class_a_overwrite}
```

## Expected behavior

```
pp Base.exception_handlers
# => {:no_method_error=>:default}

pp ClassA.exception_handlers
# => {:no_method_error=>:class_a_overwrite}

pp ClassB.exception_handlers
# => {:no_method_error=>:default}
```

## My environment

- Affects my production application: **YES**
- Ruby version: 2.5.3

**Comment by flash-gordon** [comment]
I sincerely don't think this is unexpected. Quite the opposite, copying/duping values in subclasses is unexpected for me. Mostly because you cannot opt-out of it if it's always on.
Changing the current behavior will be a major breakage as well since we often use class attributes for referencing other classes. Imagine we copy these referenced classes when we subclass
```ruby
2.7.1 :001 > Test = Class.new
2.7.1 :002 > Test.dup
 => #<Class:0x00007fe4920dd9b8>
```
That'd be a total mess 😅 
On the other hand, having an option for copying attribute values in subclasses is nice to have. Something like
```ruby
class Base
  extend Dry::Core::ClassAttributes

  defines :exception_handlers, subclass: :dup.to_proc # -> x { x } by default
  handle_exception :no_method_error, :default
end
```

Finally, in your case, it should be
```ruby
  defines :exception_handlers
  exception_handlers({}.freeze)

  def self.handle_exception(key, value)
    exception_handlers(exception_handlers.merge(key => value).freeze)
  end
```

**Comment by solnic** [comment]
oh it's THIS problem, sorry I overlooked it. OK so I wonder if maybe we should freeze by default?

**Comment by flash-gordon** [comment]
@solnic then you'll freeze classes then it'll be a problem again. Say, if you freeze Object then you won't be able to create global constants, quite unexpected side effect :) And it'll be problematic for an unprepared person to find the place where it happens. Is there any class-level macro that does it? I think they all work like dry-core.

**Comment by mbajur** [comment]
@flash-gordon it indeed worked, thank you! 🙌

**Comment by solnic** [comment]
OK I'm gonna close this for now. I wrote down a note about it so I'll revisit this before 1.0.0.
